#!/bin/bash

echo 'export PATH=/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin/:$PATH' >> /root/.profile

source /root/.profile

brew install $PKGS

gh repo clone $GIT_REPO /root/workspace

code-server --bind-addr 0.0.0.0:8080 /root/workspace
